{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <other.demo_allure.TestAllure object at 0x0000022197319250>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_b(self):\n        print('test_')\n>       assert False\nE       assert False\n\ndemo_allure.py:18: AssertionError"}, "start": 1646745394982, "stop": 1646745394983, "uuid": "7fc160a3-b480-4504-933f-4ac8968818cb", "historyId": "1ecfcb43f4ef3bde5ccc3d944b1f2302", "testCaseId": "1d7901090f334c5a1eaead3146631f21", "fullName": "demo_allure.TestAllure#test_b", "labels": [{"name": "severity", "value": "critical"}, {"name": "suite", "value": "demo_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "zhh-matebook14"}, {"name": "thread", "value": "15156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "demo_allure"}]}